line_length:
  warning: 150
  error: 200

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - r
    - g
    - b
    - i
    - x
    - y
    - z
    - e

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 600
  error: 700

function_body_length:
  warning: 100
  error: 150

disabled_rules:
  - trailing_comma
